$("#btn1").click(function(){
    Swal.fire('" DICEN QUE LA CURIOSIDAD MATO AL GATO , PERO ALMENOS MURIO SABIENDO"');
});	

$("#btn2").click(function(){
Swal.fire('"ESTABLECER METAS ES EL PRIMER PASO PARA CONVERTIR LO INVISIBLE EN LO VISIBLE"');
});	

$("#btn3").click(function(){
Swal.fire('"UNA PERSONA POSITIVA CONVIERTE SUS PROBLEMAS EN RETOS , NUNCA EN OSTACULOS."');
});	

$("#btn4").click(function(){
Swal.fire('¿QUE SERIA DE LA VIDA SI NO TUVIÉRAMOS EL VALOR DE INTENTAR ALGO NUEVO?');
});	

$("#btn5").click(function(){
Swal.fire('SI EL PLAN NO FUNCIONA CAMBIA EL PLAN PERO NO CAMBIES LA META');
});	

$("#btn6").click(function(){
Swal.fire('NO PERMITAS QUE LAS OPINIONES DE LAS DEMÁS AHOGUEN TU VOZ INTERIOR SE VALIENTE Y OBEDECE A TU CORAZÓN Y TU INTUICIÓN STEVE JOBS');
});	

